### PR TITLE
Doing a lot of cleanup in the code XML here

### PR DESCRIPTION
**Pull request by Rnen**
Figured this tool was pretty nifty to get a good overview
https://livedocumenter.barryjones.me.uk/

### CODE REVIEW

**Comment by Rnen** [comment]
Gonna do more later this week. 
@ElectronicsArchiver you might be interested in this, idk.

**Comment by ElectronicsArchiver** [comment]
> Figured this tool was pretty nifty to get a good overview https://livedocumenter.barryjones.me.uk/

> This will only work on Windows at the moment,

🠖 I'm on Linux~

**Comment by ElectronicsArchiver** [comment]
On that note, the plugin only works for windows correct?
If so, I'd add a note for that in the README.

**Comment by Rnen** [comment]
> On that note, the plugin only works for windows correct? If so, I'd add a note for that in the README.

No idea 🤷 Have no devices to test that on. If SMod works on Linux then in theory the plugin should work as well

**Pull request merged**
