### PR TITLE
Alright, probably fixed KillCommand (it works for me)

### PR DESCRIPTION
**Pull request by lordofkhaos**

### CODE REVIEW

**Comment by lordofkhaos** [comment]
Okeydokey, will do

**Comment by Rnen** [comment]
Now it's really broken, since i pushed the new files :sweat_smile:

**Comment by Rnen** [comment]
@lordofkhaos This is why doing stuff in main file is not that great :sweat_smile: 
image

**Comment by Rnen** [comment]
[Kill / Slay Command](https://trello.com/c/7mPcDOwJ/36-kill-slay-command)

**Comment by lordofkhaos** [comment]
That should work

**Comment by Rnen** [comment]
Had to manually go through all conflicts >.<

**Comment by Rnen** [comment]
Yeah... that didnt go well
https://github.com/Rnen/AdminToolbox/commit/025cdc65c401918ec7f47d5c6c9e094edb987c6a

**Comment by lordofkhaos** [comment]
o.0 my B lol

**Pull request merged**
